### ISSUE TITLE
New BETA release

### ISSUE THREAD

**Issue by larryTheCoder** [TheSolidCrafter/ASkyBlock-Nukkit#20]
# Todo list
- [x] Remove useless code resulting issues and problems
- [x] Get rip out of the old listeners code
- [ ] Add new entities (Skull, Banner(1.2 Update), Hopper, Minecarts, etc)
- [ ] Change Island ID to UUID
- [x] Rewrite spawning base
- [ ] Implements full database variants (yaml, sql, mysql, etc)
- [ ] Complete control of command usage with granular permissions (ie specific biomes for setbiome)
- [ ] Allow spawn/tp on your island at a configurable location
- [ ] Use GriefPrevention trust commands to work in teams
- [ ] Change the biome of a block, chunk or entire island
- [ ] Limit entity spawning per island
- [ ] Automatic removal of inactive islands
- [x] Configurable island layouts (linear & spiral planned)
- [x] Add an island messaging channel so you can chat within your island

## Future local update
- Fix most variant bugs
- Get rip out the old listeners
- Fix some nonworking commands
- Protected access on API listeners

## What will I do when all of these done?
I will release the **BETA** version of ASkyBlock

## How do you want to contribute with us
Send feedback in this issue or create a pull request

**Comment by NycuRO** [comment]
@larryTheCoder Hmm..
I think the news Entityes is added by @yescallop in 1.2, and you can use Nukkit instanceof import . 👍 

(P.S. @Creeperface01 work on these blocks)

**Comment by NycuRO** [comment]
Update @larryTheCoder ?

**Comment by larryTheCoder** [comment]
Coming soon

**Comment by NycuRO** [comment]
@larryTheCoder So?

**Comment by NycuRO** [comment]
lol, thx.

**Comment by larryTheCoder** [comment]
@NycuRO Not a problem... I still looking for new members to join. I might be offline for a several weeks... I.. Well.. I will be back with surprising updates 😄.
Such as:
- Improved help command
![improvies](https://user-images.githubusercontent.com/15889642/31230650-334e0d12-aa17-11e7-8b5e-8567d55096c1.jpg)
- Panels: Added panels for user to interacting with challenges and islands in **1.2 Version**
- Admin: Fully added admin features for admin `Editing and Deleting` Islands
- Auto Delete: Remove the old islands in a year or two

Lot of update to coming this fall (It might release after the Super Duper Graphics Pack Update)

**Comment by NycuRO** [comment]
@larryTheCoder oke oke

**Comment by NycuRO** [comment]
Can you try implement Achievments and combine with Modals ? (When creating and others.) @larryTheCoder

**Comment by larryTheCoder** [comment]
Of course

**Comment by larryTheCoder** [comment]
Of course
